### ISSUE TITLE
How to Communicate Over Wifi?

### ISSUE THREAD

**Issue by SMKH-PRO** [aboozaid/react-native-wifi-hotspot#8]
The library's ReadMe says that we can create **ShareIt** like apps with this library, But there are no documentation about **"How to Share Files"**  How to communicate with connected devices?

How to share file or a string to the connected device.

**Comment by aboozaid** [comment]
The library helps you to communicate with your mobile's hotspot in order to open it and change its configurations after that you can use @react-native-tcp to open a socket with a returned IP from the lib.

**Comment by peckyboy** [comment]
I was also hoping to get a description on how to go about it. 
Very dissapointing.

**Comment by tangtai** [comment]
Is this still possible to change the wifi / hotspot settings in android. I try to create wifi hot spot using android java code, i wasn't able to do it because the permission restrictions, since some of the permissions required are only for system apps, the API for "setwifiapenabled" is not public api and google changed it for new build API level. what did you used to build this library?

**Comment by aboozaid** [comment]
@tangtai you can use android reflection.
